
// Number one

// function lib(name, subject){
//     var output = name + "'s favorite subject is " + subject
//     return output
// }

// console.log(lib('Chris','Coding'))


// Number two

// function tip(price, service){
//     if( service == 'good'){
//     var output1 = price * .20
//     return output1.toFixed(2)
// }
//     else if( service == 'fair'){
//     var output2 = price * .15
//     return output2.toFixed(2)
//     }

//     else if( service == 'bad'){
//     var output3 = price * .10
//     return output3.toFixed(2)
// }
// }
// console.log(tip(100, 'fair'));

// Number 3


// function total(price, service){
//     if( service == 'good'){
//     var output1 = price * 1.20
//     return output1.toFixed(2)
// }
//     else if( service == 'fair'){
//     var output2 = price * 1.15
//     return output2.toFixed(2)
//     }

//     else if( service == 'bad'){
//     var output3 = price * 1.10
//     return output3.toFixed(2)
// }
// }
// console.log(total(100, 'fair'));

// Number 4

// for(var count = 1; count < 11; count = count + 1){
    
//         console.log(count)
//     }

//     count1 = 0;
//     while (count1 <= 9) {
//     count1 = count1 + 1;
//     console.log(count1);
// }

// Number 5
